# Generated by Django 5.0.6 on 2024-06-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sf_user_id',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
