# Generated by Django 5.0.6 on 2024-08-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_date', models.DateTimeField()),
                ('payout_scheduled_date', models.DateTimeField()),
                ('payment_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payout_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payout_entry_id', models.CharField(blank=True, max_length=64, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('transaction_type', models.CharField(blank=True, max_length=64, null=True)),
                ('transaction_source_type', models.CharField(blank=True, max_length=64, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
