# Generated by Django 5.0.6 on 2024-06-17 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('salesforce_account_id', models.CharField(blank=True, max_length=18, null=True)),
                ('salesforce_account_name', models.CharField(blank=True, max_length=64, null=True)),
                ('rep_name', models.CharField(blank=True, max_length=64, null=True)),
                ('rep_from_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
