# Generated by Django 5.0.6 on 2024-06-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_smstracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstracker',
            name='account_to_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
