# Generated by Django 5.0.6 on 2024-07-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0003_smstracker_account_to_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtracker',
            name='phone_source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
