# Generated by Django 5.0.6 on 2024-07-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0004_marketingtracker_phone_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtracker',
            name='keyword',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
