# Generated by Django 5.0.6 on 2024-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0005_marketingtracker_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtracker',
            name='account_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
