# Generated by Django 5.0.6 on 2024-10-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0006_marketingtracker_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingtracker',
            name='call_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingtracker',
            name='number_called_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
