# Generated by Django 5.0.6 on 2025-01-20 22:38

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0007_marketingtracker_call_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=0, max_length=18)),
                ('customer_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('tracking_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('tracking_number_name', models.CharField(blank=True, max_length=64, null=True)),
                ('recording_url', models.CharField(blank=True, max_length=128, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
