# Generated by Django 5.0.6 on 2025-01-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0008_phonecalls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecalls',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
