# Generated by Django 5.0.6 on 2025-02-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0009_alter_phonecalls_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonecalls',
            name='sentiment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
