# Generated by Django 5.0.6 on 2025-02-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0010_phonecalls_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecalls',
            name='customer_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='phonecalls',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
