# Generated by Django 5.0.6 on 2025-03-25 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0011_alter_phonecalls_customer_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnneagramCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'checked_out'), (2, 'expired'), (3, 'complete')], default=0)),
                ('code', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnneagramTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'complete'), (2, 'canceled'), (3, 'expired')], default=0)),
                ('department', models.IntegerField(choices=[(0, 'other'), (1, 'sales'), (2, 'ops')], default=0)),
                ('order_number', models.IntegerField(default=0)),
                ('test_taken_date', models.DateField(blank=True, null=True)),
                ('result_1', models.IntegerField(default=0)),
                ('score_1', models.IntegerField(default=0)),
                ('result_2', models.IntegerField(default=0)),
                ('score_2', models.IntegerField(default=0)),
                ('result_3', models.IntegerField(default=0)),
                ('score_3', models.IntegerField(default=0)),
                ('fullname', models.CharField(blank=True, max_length=125, null=True)),
                ('email', models.CharField(blank=True, max_length=125, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('testing', models.IntegerField(default=0)),
                ('enneagram_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprojects.enneagramcode')),
            ],
        ),
    ]
