# Generated by Django 5.0.6 on 2025-04-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0013_quickbookstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('reference', models.TextField(blank=True, null=True)),
                ('posted_to_qbo', models.BooleanField(default=False)),
                ('qbo_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
