# Generated by Django 5.0.6 on 2025-06-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0014_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallRailCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('call_date_time', models.DateTimeField()),
                ('call_source', models.CharField(blank=True, max_length=255)),
                ('call_keywords', models.TextField(blank=True)),
                ('call_referrer', models.TextField(blank=True)),
                ('call_medium', models.CharField(blank=True, max_length=255)),
                ('call_landing_page', models.TextField(blank=True)),
                ('call_campaign', models.CharField(blank=True, max_length=255)),
                ('call_recording', models.URLField(blank=True)),
            ],
        ),
    ]
