# Generated by Django 5.0.6 on 2025-07-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0015_callrailcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrailcall',
            name='call_recording',
            field=models.URLField(blank=True, null=True),
        ),
    ]
