# Generated by Django 5.0.6 on 2025-07-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0016_alter_callrailcall_call_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrailcall',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
