# Generated by Django 5.0.6 on 2025-07-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0017_callrailcall_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrailcall',
            name='call_agent_speaker_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='callrailcall',
            name='call_customer_speaker_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='callrailcall',
            name='call_sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='callrailcall',
            name='call_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callrailcall',
            name='call_transcription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='callrailcall',
            name='call_utm_content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callrailcall',
            name='gclid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='callrailcall',
            name='prior_calls',
            field=models.IntegerField(default=0),
        ),
    ]
