# Generated by Django 5.0.6 on 2025-07-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0018_callrailcall_call_agent_speaker_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrailcall',
            name='call_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_landing_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_referrer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
