# Generated by Django 5.0.6 on 2025-07-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0019_alter_callrailcall_call_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrailcall',
            name='call_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='call_utm_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='gclid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='number_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='callrailcall',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
