# Generated by Django 5.2.5 on 2025-09-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airparserconfig',
            options={'verbose_name': 'AirParser API Configuration', 'verbose_name_plural': 'AirParser API Configurations'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='airparser_schema_id',
        ),
        migrations.AddField(
            model_name='supplier',
            name='airparser_inbox_id',
            field=models.CharField(blank=True, help_text='AirParser inbox ID (e.g., 68bf19bf8fb7546120660a49)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airparserconfig',
            name='api_key',
            field=models.CharField(help_text='Your AirParser API key', max_length=200),
        ),
        migrations.AlterField(
            model_name='airparserconfig',
            name='api_url',
            field=models.URLField(default='https://api.airparser.com', help_text='AirParser API base URL'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, help_text="Supplier's contact email", max_length=254, null=True),
        ),
    ]
