# Generated by Django 5.2.5 on 2025-09-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('po_processing', '0002_alter_airparserconfig_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AirParserConfig',
        ),
    ]
